apiVersion: argoproj.io/v1alpha1 # Changed from apps/v1
kind: Rollout # Changed from Deployment
# --- Everything below this comment is the same as a deployment ---
metadata:
  name: example-rollout
spec:
  replicas: 5
  selector:
    matchLabels:
     app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.20.1
    ports:
    - containerPort: 80
  minReadySeconds: 30
  revisionHistoryLimit: 3
  strategy:
# --- Everything above this comment are the same as a deployment ---
    canary: # A new field for configurable Canary options
      maxSurge: "10%"
      maxUnavailable: 0
      steps:
      - setWeight: 10
      - pause:
          duration: 30 #seconds
      - setWeight: 50
      - pause: {}
