apiVersion: v1
kind: Service
metadata:
  name: myfirstservice
  labels:
    version: abc1
spec:
  type: NodePort
  ports:
    - nodePort: 32000
      port: 9000
      targetPort: 80
  selector:
     type: front-node
